project:
  type: website
  render:
    - "*.qmd"

website:
  title: "Formaci贸n b谩sica de R: Manipulaci贸n de datos y an谩lisis input-output"
  navbar:
    background: dark
    logo: "materiales/images/R_logo.svg.png"
    right:
       - icon: envelope
         href: mailto:kamal.romero-sookoo@ext.ec.europa.eu

    left:
      - href: index.qmd
        text: Home
      - text: Secciones
        menu:
        - text: "Introducci贸n"
          href: materiales/00_intro.qmd
        - text: "Data frames"
          href: materiales/01_dataFrames.qmd
        - text: "dplyr vs data.table"
          href: materiales/03_dplyrvsDatatable.qmd
        - text: "Manipulaci贸n de datos"
          href: materiales/04_dataManipulation.qmd
        # - text: "ggplot2"
        #   href: materiales/05_ggplot2.qmd
        #   #target: "_blank"
        # - text: "Regression analysis"
        #   href: materials/10_regression.qmd
      #   - text: "Thank you "
      #     href: materials/8_closing.qmd
      #     target: "_blank"
      - text: Material adicional
        menu:
        - text: "Programaci贸n b谩sica"
          href: materiales/08_programming.qmd
        # - text: "Data Manipulation Part I Exercises"
      #     href: materials/2_data_manipulation_1-exercises.qmd
      #   - text: "Data Engineering Exercises"
      #     href: materials/3_data_engineering-exercises.qmd
      #   - text: "Arrow In-Memory Workflow Exercises"
      #     href: materials/5_arrow_single_file-exercises.qmd
      #   - text: "Data Manipulation Part II Exercises"
      #     href: materials/4_data_manipulation_2-exercises.qmd


format:
  html:
    theme: journal
    #css: styles.css
    toc: true
    toc-depth: 4
    link-external-newwindow: true

# editor: visual
# engine: knitr
# execute:
#   freeze: auto